org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
# IntelliJ IDEA chưa tương thích tốt với configuration cache của Loom
org.gradle.configuration-cache=false

# Fabric Properties — kiểm tra version mới nhất tại https://fabricmc.net/develop
minecraft_version=1.21.11
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Mod Properties
mod_version=1.0.0
maven_group=com.thanh.autotrade
archives_base_name=autotrade

# Dependencies
fabric_api_version=0.141.6+1.21.11
